google/devx-tools

waterfall/java/com/google/waterfall/client/WaterfallClient.java

The goal is to ease mocking the client without writing delegation.

Update Java WaterfallClient to make it non-final.

---

waterfall/golang/forward/BUILD
waterfall/golang/forward/forward_bin.go

This allows having multiple aliases for a single device and forward
everything without an extra hop.
eg and android emulator can be referenced with the following names:
- emulator-${EMULATOR_TELNET_PORT}
- localhost:${ADB_PORT}
- 127.0.0.1:${ADB_PORT}

Allow listening on multiple interfaces for connections to forward.

---

.bazelrc
WORKSPACE

- Add flags in .bazelrc so that broken changes introduced in recent
version of bazel don't break dependencies that still rely on old
behavior.
- Fetch io_grpc_grpc_java before everything else. Both go rules and
java_grpc depend on protobuf repo, however the go rules version depends
on a version which is broken for java
(https://github.com/bazelbuild/rules_go/pull/2105 addresses this).
Until that change is not submitted we need to force the java dep to be
downloaded first. Note that we cant revert to an older go rules version
since they are not compatible with newer bazel binaries (and no way to
work around via bazelrc).
Correct soulution is to have a repositories.bzl that loads common
dependencies up front in order to avoid this issues.

Fix broken builds

---

waterfall/golang/mux/BUILD
waterfall/golang/mux/addr.go
waterfall/golang/mux/conn.go
waterfall/golang/mux/message.go
waterfall/golang/mux/mux.go
waterfall/golang/mux/mux_test.go
waterfall/proto/waterfall.proto

gRPC multiplexing service
Multiplexer allows multiplexing multiple virtual connections over a single connections.
It has two main components
- a net Listener that wraps a base Listener
(Accept can only be called once on this listener) that is used to create
a gRPC service that exposesa single method (NewStream) which simply
returns a new bidirectional stream when its called.
- a conncection builder that creates new net.Conn by calling NewStream
on a gRPC cliet that dials the base listener of the service.

Multiplexing grpc service

---

.continuous_integration/postsubmit.yml
waterfall/golang/forkfd/BUILD
waterfall/golang/forkfd/forkfd.go
waterfall/golang/forward/BUILD
waterfall/golang/forward/forward_bin.go
waterfall/golang/mux/conn.go
waterfall/golang/mux/mux.go
waterfall/golang/mux/mux_test.go
waterfall/golang/server/BUILD
waterfall/golang/server/server_bin.go

Introduced forkfd a new binary that listens for incoming connections to be
multiplexed and starts the server forking the process with a dup of the
connection fd. The forwarder can then connect to the server over
multiplexed streams on that endpoint.
forkfd opens a socket that can only handle a single stream at a time.
Once a connection is established the waterfall process is forked with
access to that fd. Waterall uses that connection to start a
Multiplexer service which is then used to start the waterfall server.
forfd blocks until the waterfall process is done since the communication
channel opened by forkfs is only suppose to ever have a single active
connection.
Also commit history includes merge and postsubmit file because git history got messed up and coulndt restore it.

Allow running server forwarder over multiplex connections.

---

waterfall/golang/client/adb/adb.go

Originally ADB didnt report the exit status from commands
and on some later version started to report it.
Enable both modes via env variable PROPAGATE_STATUS_CODE.
Default mode does not propagate

Add option to propagate status code from shell commands

---

waterfall/golang/adb/adb.go

This will allow installing the usb service when bootstrapping

Add install function to adb client

---

.continuous_integration/postsubmit.yml

requires libusb to be present on host.

Disable forward_usb_bin target in buildkyte

---

waterfall/golang/forward/forward_bin.go

Configure forward_bin's logger to print source file names and line numbers when logging.

Log line numbers in forward_bin

---

waterfall/golang/server/server.go

Non-streamed installs were missing the "install" command.
E.g.
pm /data/local/tmp/247277532.apk
now becomes
pm install /data/local/tmp/247277532.apk

Fix non-streamed installs

---

waterfall/golang/server/server.go

We were incorrectly ignoring the first argument in the streamed install case.

Fix issue with streamed installs

---

waterfall/golang/client/adb/BUILD.bazel
waterfall/golang/forkfd/BUILD.bazel
waterfall/golang/forward/BUILD.bazel
waterfall/golang/net/qemu/BUILD.bazel
waterfall/golang/server/BUILD.bazel

- remove most architecture/os specific go builds and prefer use of
--platforms blaze flag

Simplify build files

---

waterfall/golang/client/adb/adb.go
waterfall/golang/client/adb/adb_bin.go
waterfall/golang/forward/ports/ports.go
waterfall/golang/forward/ports/ports_test.go
waterfall/golang/server/server.go
waterfall/golang/server/server_bin.go
waterfall/proto/waterfall.proto

For regular forwarding (i.e. from host to device) for each new connection
the client (here ports_bin) can simply make an RPC Forward call to create a
forwarding stream. The converse is not true (the server can't make calls
outside the device). To get around this we do the following:
1) initially the client sends an StartForward request to the server.
This rpc call needs to be alive for the duration of the forwarding session.
2) Upon receiving such request, the server listens for connections on the
desired socket. Each time it establish a new connection, it notifies the
client sending a new Forward message of type OPEN via the StartForward rpc stream.
3) When the client gets this message, it makes a ReverseForward rpc call to the
server.
4) The server then pipes the connection to the …

Add reverse forwarding support to waterfall

---

waterfall/golang/forward/ports/ports.go
waterfall/golang/server/BUILD.bazel
waterfall/golang/server/server.go

In ReverseFoward server implementation, the OPEN request from ports_bin may arrive out of order, causing it to be matched to the wrong connection opened in StartReverseForwarding. Instead, map each connection to a connection id, ports_bin will always refer to the id when sending an OPEN request to ReverseForward, thus matching up with the right connection

Fix concurrency bug in waterfall reverse forwarding

---

waterfall/golang/server/server_bin.go

Write logs to /dev/kmsg if the file descriptor is passed to the Waterfall server by init.

Send Waterfall server logs to the kernel log when possible.

---

BUILD.bazel
WORKSPACE
waterfall/golang/adb/BUILD.bazel
waterfall/golang/aoa/BUILD.bazel
waterfall/golang/bootstrap/BUILD.bazel
waterfall/golang/client/BUILD.bazel
waterfall/golang/client/adb/BUILD.bazel
waterfall/golang/constants/BUILD.bazel
waterfall/golang/forkfd/BUILD.bazel
waterfall/golang/forward/BUILD.bazel
waterfall/golang/forward/ports/BUILD.bazel
waterfall/golang/mux/BUILD.bazel
waterfall/golang/net/qemu/BUILD.bazel
waterfall/golang/server/BUILD.bazel
waterfall/golang/server/testing/BUILD.bazel
waterfall/golang/stream/BUILD.bazel
waterfall/golang/testutils/BUILD.bazel
waterfall/golang/utils/BUILD.bazel
waterfall/java/com/google/waterfall/tar/BUILD.bazel
waterfall/javatests/com/google/waterfall/client/BUILD.bazel
waterfall/javatests/com/google/waterfall/tar/BUILD.bazel
waterfall/proto/BUILD.bazel

Reverts google/devx-tools#91
It was originally though this led to OOMs for other processes on the device. However, the report came from one test and undoing this change did nothing.

Revert "Revert "Update several dependencies: Go Starlark rules, gRPC, Protobuf, etc. …""

---

BUILD.bazel
WORKSPACE
waterfall/golang/adb/BUILD.bazel
waterfall/golang/aoa/BUILD.bazel
waterfall/golang/bootstrap/BUILD.bazel
waterfall/golang/client/BUILD.bazel
waterfall/golang/client/adb/BUILD.bazel
waterfall/golang/constants/BUILD.bazel
waterfall/golang/forkfd/BUILD.bazel
waterfall/golang/forward/BUILD.bazel
waterfall/golang/forward/ports/BUILD.bazel
waterfall/golang/mux/BUILD.bazel
waterfall/golang/net/qemu/BUILD.bazel
waterfall/golang/server/BUILD.bazel
waterfall/golang/server/testing/BUILD.bazel
waterfall/golang/stream/BUILD.bazel
waterfall/golang/testutils/BUILD.bazel
waterfall/golang/utils/BUILD.bazel
waterfall/java/com/google/waterfall/tar/BUILD.bazel
waterfall/javatests/com/google/waterfall/client/BUILD.bazel
waterfall/javatests/com/google/waterfall/tar/BUILD.bazel
waterfall/proto/BUILD.bazel

Reverts google/devx-tools#92
Once again reverting. 32 bit ARM binaries built with this commit lead to crashes at runtime. Though the devices successfully build so it might be snapshot related.
BUG: Bad page map in process android.bg  pte:f42dbb79 pmd:48319831
addr:8a003000 vm_flags:00100073 anon_vma:c8306760 mapping:c826757c index:3c1
vma->vm_file->f_op->mmap: shmem_mmap+0x0/0x30
CPU: 0 PID: 1148 Comm: android.bg Not tainted 3.10.0+ #1
[<c0013744>] (unwind_backtrace+0x0/0xec) from [<c0011860>] (show_stack+0x10/0x14)
[<c0011860>] (show_stack+0x10/0x14) from [<c00bbbe4>] (print_bad_pte+0x118/0x1a8)
[<c00bbbe4>] (print_bad_pte+0x118/0x1a8) from [<c00bc8b4>] (vm_normal_page+0x6c/0xb8)
[<c00bc8b4>] (vm_normal_page+0x6c/0xb8) from [<c0126a04>] (smaps_pte_range+0xf0/0x274)
[<c0126a04>] …

Revert "Revert "Revert "Update several dependencies: Go Starlark rules, gRPC, Protobuf, etc. …"""

---

waterfall/golang/server/server.go
waterfall/proto/waterfall.proto

Respond to the client with the selected port when a client requests forwarding for any available port (tcp:0 or udp:0).

Support for reverse tcp:0

---

waterfall/golang/server/server.go

This will cause these logs to write to the kernel log instead of stdout.

Replace 'fmt.Printf' calls with 'log.Printf'

---

waterfall/golang/server/server.go

Because errors are passed to clients through the Transfer message on
write failures, this ensures that any errors encountered during
untarring will be passed back to clients.

Call 'CloseWithError' on the error returned by 'stream.Untar()'

---

waterfall/golang/server/server.go
waterfall/golang/server/server_bin.go
waterfall/golang/server/snapshot.go

When rebooting in some circumstances, it is possible for this file to
disappear.

Store snapshot status in a persistent property instead of a file.

---

WORKSPACE
waterfall/golang/net/qemu/BUILD.bazel
waterfall/golang/net/qemu/qemu.go
waterfall/golang/server/BUILD.bazel
waterfall/golang/server/server_bin.go

This enables Vsock in Waterfall. It only works with a custom Emulator build.

Vsock with lib

---

waterfall/golang/server/server.go

Occasionally, VSock connections stay open perpetually, even after GracefullStop has been
called.

Call server.Stop after 5s if the server has not gracefully shutdown.

---

BUILD.bazel
WORKSPACE

Move the toolchain/dependecy calls to the end of the file to avoid
conflicts with other rules.
Ran 'bazel run //:gazelle -- update-repos' on the 'go_repository' rules
to ensure they're up to date.

Update WORKSPACE to use the latest version of Go + deps.

---

waterfall/prebuilt/arm/BUILD.bazel
waterfall/prebuilt/arm64/BUILD.bazel
waterfall/prebuilt/x86/BUILD.bazel

According to Allstar, this is a security policy violation: https://github.com/ossf/scorecard/blob/main/docs/checks.md#binary-artifacts

Delete waterfall prebuilt binaries.

---

waterfall/golang/server/server.go

Add more mutex locking of maps to avoid concurrent map accesses.
Delete connMap entries as soon as they're retrieved. They only need to be retrieved from the map once.

Guard more concurrent map usages and delete connMap entries.

---

waterfall/golang/net/qemu/qemu.go

This change must have gotten lost in my last commit after the large rebase from master.

Enable vsock when driver is available

---

waterfall/golang/net/qemu/qemu.go

In practice, this retry only happens before the waterfall forwarder
starts up - in which case, it doesn't make sense to spam the
emulator with connection retries.

Increase wait time between retries to 500ms.

---

waterfall/golang/net/qemu/qemu.go
waterfall/golang/server/server.go
waterfall/golang/server/server_bin.go

The gRPC timeout is switched back to 1year, since the 10s timeout causes
connections to occasionally disconnect. Updates will be made on the
forwarder side to close lingering connections instead.
Add 500ms delays at each point a connection retry is possible. This
should prevent waterfall from busy-looping on reads and using 100% CPU.

Update waterfall to handle vsock connections more robustly.

---

waterfall/golang/server/server.go

If the device network is degraded, it's possible this error will not make it back to the client.

Log error when reverse forwarding fails.
