WORKSPACE
Change-Id: Ife15a9b36dcb4b0a85a1556dca3a82dd0c5cf3c3
=> update java grpc version (fixes compatibility issue with bazel version)

waterfall/golang/client/adb/BUILD, waterfall/golang/client/adb/adb.go, waterfall/golang/client/adb/adb_bin.go
This will allow to create binaries with different grpc options, simplifying internal vs external differences.
=> Refactor adb client into library and binary

waterfall/golang/client/adb/adb_bin.go
This allows connecting to servers in non default addresses
=> Use address as is when user specifies protocol

waterfall/java/com/google/waterfall/usb/UsbService.java
This allows to test the setup/connection between the host and the device
without the need to bring any additional components
=> Add echo action to usb service.

.continuous_integration/postsubmit.yml, BUILD.gousb, WORKSPACE, waterfall/golang/aoa/BUILD, waterfall/golang/aoa/aoa.go, waterfall/golang/aoa/aoa_test.go, waterfall/golang/aoa/aoa_utils_bin.go, waterfall/java/com/google/waterfall/usb/UsbService.java
AOA provides a ReadWriteCloser implementation on top of a USB connection
using the Android open acccessory protocol. It uses libusb/gousb in
order to talk to the usb driver.
Additionally, added a sample utility to open an echo shell to the
devices in order to manually test the connection.
=> AOA package

waterfall/golang/forkfd/BUILD, waterfall/golang/forkfd/forkfd.go
This allows us to start the binary from adb shell and detach us so
we dont have to keep the adb session open
=> Add option to forkfd to fork itself

waterfall/golang/forward/BUILD, waterfall/golang/forward/forward_usb_bin.go
Keep this in its own binaray since it links against libusb
=> USB connection forwarder binary

waterfall/golang/forkfd/forkfd.go
No need to keep it around and loop will never exit
=> Close the connection after dupping

waterfall/golang/net/qemu/control.go
XXX_Size is implementation details and shouldnt be used
=> use prot.Size insted of XXX_Size

waterfall/golang/client/adb/adb.go, waterfall/golang/client/client.go, waterfall/golang/server/server.go, waterfall/proto/waterfall.proto
Handles:
- legacy install
- Streamed install with pm
- Streamed install with cmd
Currently single apk install is supported
=> Server side install implementations

.bazelrc, WORKSPACE, waterfall/golang/forward/BUILD
- + fixes to work with latest versions of tools
- ran buildifier
=> Update WORKSPACE file

waterfall/golang/client/client.go, waterfall/golang/server/server.go
1) CLient should not block on stdin copy operation
2) Use StdinPipe when piping in the server -> golang
blocks on copies when stdin is not file, therefore
even if the process exits cmd.Wait will still block
see https://github.com/golang/go/issues/7990.
=> Handle process termination correctly when stdin is piped

WORKSPACE, waterfall/golang/forward/BUILD.bazel, waterfall/golang/forward/forward_bin.go, waterfall/golang/server/BUILD.bazel, waterfall/golang/server/server_bin.go, waterfall/golang/utils/addr.go
VSOCK support for cuttlefish devices
=> Add vsock support

WORKSPACE, waterfall/golang/server/server_bin.go
=> Don't timeout waterfall connections

waterfall/golang/stream/stream.go
Fix an issue where waterfall stream read will non-blockingly return even when there's no incoming msgs so the CPU burns when looping read
=> Fix an issue with waterfall stream

waterfall/golang/net/qemu/qemu.go
Add some more context so we know exactly where forwarder initiation fails.
Also avoid unnecessary Chdir calls if the working directory is the same as the emulator working directory.
=> Add more context to errors when setting up a qemu connection.

BUILD.bazel, WORKSPACE, waterfall/golang/adb/BUILD.bazel, waterfall/golang/aoa/BUILD.bazel, waterfall/golang/bootstrap/BUILD.bazel, waterfall/golang/client/BUILD.bazel, waterfall/golang/client/adb/BUILD.bazel, waterfall/golang/constants/BUILD.bazel, waterfall/golang/forkfd/BUILD.bazel, waterfall/golang/forward/BUILD.bazel, waterfall/golang/forward/ports/BUILD.bazel, waterfall/golang/mux/BUILD.bazel, waterfall/golang/net/qemu/BUILD.bazel, waterfall/golang/server/BUILD.bazel, waterfall/golang/server/testing/BUILD.bazel, waterfall/golang/stream/BUILD.bazel, waterfall/golang/testutils/BUILD.bazel, waterfall/golang/utils/BUILD.bazel, waterfall/java/com/google/waterfall/tar/BUILD.bazel, waterfall/javatests/com/google/waterfall/client/BUILD.bazel, waterfall/javatests/com/google/waterfall/tar/BUILD.bazel, waterfall/proto/BUILD.bazel
=> Revert "Update several dependencies: Go Starlark rules, gRPC, Protobuf, etc. …"

waterfall/golang/server/server.go
This is an attempt to ensure we get an actual port assigned by the kernel
=> Retry creating the listener when doing a reverse forward

waterfall/golang/server/server.go
This is already handled in StopReverseForward.
=> Do not delete/close connections in ReverseForward.

waterfall/golang/server/server.go
Ignore a non-zero error code from any of the various shell commands used to install an APK if "Success" is in the output of the command. We somewhat frequently see cases where the exit code is -1 which means the process either didn't exit or was terminated by a signal. See: https://github.com/google/devx-tools/pull/new/install
In these cases we should try considering the result successful anyway.
=> APK install improvements

WORKSPACE, waterfall/golang/server/BUILD.bazel
NDK. Add the NDK/SDK rules to WORKSPACE.
=> Update waterfall server_bin target so it is linkable against the android
